### ISSUE TITLE
Combatify modifies shield animation in third person

### ISSUE THREAD

**Issue by StunfMC** [Alexandra-Myers/Combatify#47] opened 2023-09-10 16:03 UTC
The third person shield animation with Combatify installed has incorrect positioning for a frame during blocking, making the shield animation look choppy.

**Comment by Alexandra-Myers** [comment] 2023-09-24 16:24
technically fixed but cannot be completely fixed

**Comment by DreamSt4n** [comment] 2023-09-27 20:30
This is still an issue. Please reopen.

**Comment by Alexandra-Myers** [comment] 2023-09-27 21:13
do you have sword blocking enabled?

**Comment by DreamSt4n** [comment] 2023-09-27 21:38
No, but the issue persists either way.

**Comment by StunfMC** [comment] 2024-01-10 19:15
Technically fixed in this [commit](https://github.com/Alexandra-Myers/Combatify/commit/5b5c2256abfe478696c8817009b982049d087bd2) but breaks sword blocking due to some modifications.

**Comment by zOnlyKroks** [comment] 2024-01-10 19:26
by removing sword blocking ;V

**Comment by StunfMC** [comment] 2024-01-10 23:13
It still exists, all I did was prevent the sword blocking to generate. I explained this in my comment, and rewriting the sword blocking code is the only way to fix this bug. I don’t plan on my commit being used since it breaks Sword Blocking but it’s just an idea with rewriting the code.

**Comment by Alexandra-Myers** [comment] 2024-01-10 23:16
The issue is, you don't even understand what that code does. It's not even the code responsible for causing this issue. This is just a band-aid fix which doesn't fix the underlying issue.

**Comment by StunfMC** [comment] 2024-01-10 23:18
I’m not saying it is the code responsible, and I am not planning this commit to be used. It’s just a proposed “fix” but it breaks Sword Blocking. I have plans to take a further look and I apologize if I didn’t make myself clear before.

**Comment by Alexandra-Myers** [comment] 2024-01-13 02:13
Anyways, fixed in 1.1.8.1, better solution needed but should be fine for most.

**Closed by Alexandra-Myers** 2024-01-13 02:13 UTC
